### ISSUE TITLE
Exception not catched

### ISSUE THREAD

**Issue by libremente** [italia/publiccode-parser-go#10]
In a publiccode.yml, when a key should contain a boolean but, instead, it contains a string, the `pcvalidate` generates this output:
```
panic: interface conversion: interface {} is string, not bool

goroutine 1 [running]:
github.com/italia/publiccode-parser-go.(*Parser).checkDependencies(0xc4200eae00, 0xc420298d70, 0xe, 0xc420283840, 0xc4202000f0, 0x781801, 0x6c8f20, 0xc4202000f0, 0xc420298d68)                                                              
        /go/src/github.com/italia/publiccode-parser-go/check_dependencies.go:11 +0x67d
github.com/italia/publiccode-parser-go.(*Parser).decodeArrObj(0xc4200eae00, 0xc420298d70, 0xe, 0xc420283840, 0x1, 0xc420093f3c)                                                                                                              
        /go/src/github.com/italia/publiccode-parser-go/keys.go:391 +0x1216
github.com/italia/publiccode-parser-go.(*Parser).decoderec(0xc4200eae00, 0xc420093f30, 0x9, 0xc42008b860, 0x1, 0x1, 0x0)                                                                                                                     
        /go/src/github.com/italia/publiccode-parser-go/parser.go:157 +0x481
github.com/italia/publiccode-parser-go.(*Parser).decoderec(0xc4200eae00, 0x0, 0x0, 0xc42008b7a0, 0x0, 0xc4200960b0, 0x0)                                                                                                                     
        /go/src/github.com/italia/publiccode-parser-go/parser.go:167 +0xe80
github.com/italia/publiccode-parser-go.(*Parser).Parse(0xc4200eae00, 0xc4200aa900, 0x6f4, 0x8f4, 0x8f4, 0x0)
        /go/src/github.com/italia/publiccode-parser-go/parser.go:59 +0x123
github.com/italia/publiccode-parser-go.(*Parser).ParseFile(0xc4200eae00, 0x7ffd0aae22b8, 0xe, 0x744550, 0x1b)
        /go/src/github.com/italia/publiccode-parser-go/parser.go:76 +0x88
main.main()
        /go/src/github.com/italia/publiccode-parser-go/pcvalidate/pcvalidate.go:35 +0x2bd
```
since this happened in two cases already, maybe it can be safer to handle such a case, or at least fail safely.
Changing the boolean value in the yml into a real boolean works as expected.

**Comment by libremente** [comment]
This happens also with phone numbers. Pretty serious bug.

**Comment by ododa** [comment]
I wanted to give this issue a go if no one else is working on it.

**Comment by sebbalex** [comment]
Thanks @ododa going to assign this one to you

**Comment by bfabio** [comment]
#79 fixes it. Keeping this issue opened so we can address the [phone numbers remark](https://github.com/italia/publiccode-parser-go/issues/10#issuecomment-537075068) as well

**Comment by ododa** [comment]
Morning @bfabio . I wanted to continue working on a fix for the phone numbers issue as well, but I would need an example yaml that shows it in practice please.

**Comment by bfabio** [comment]
@ododa I can't trigger a crash using

* `01234`
* `+01234`
* `1.2e+34`
* `.inf`
* `true`
* `"true"`

We need better validation for phone number (and that's work for #74), but it looks like this crasher is gone.

@libremente, what was the original input that made it crash on phone numbers?

**Comment by ododa** [comment]
@bfabio , I did some tests on my own and couldn't cause a crash. @libremente , we kind of need your input on this please :).

**Comment by libremente** [comment]
Hi, all. Unfortunately I cannot remember how to correctly reproduce the phone number issue. I tried different combinations and it looks OK now so maybe it has already been fixed. I'd close the issue for the moment. Thanks for the efforts!

**Comment by ododa** [comment]
Thank you @libremente . Can you please close the issue then @bfabio ?
