### ISSUE TITLE
Use go:embed instead of go-bindata

### ISSUE THREAD

**Issue by bfabio** [italia/publiccode-parser-go#134]
Support to embed files was added natively in Go 1.16 with [go:embed](https://pkg.go.dev/embed), we should drop `go-bindata` in favor of it.

**Comment by Ph0tonic** [comment]
Hello,
I have created a PR, let me know if I need to change anything.

**Comment by bfabio** [comment]
@Ph0tonic Going to review it ASAP, thanks! :pray:
