### ISSUE TITLE
Tests don't run on Pull Requests

### ISSUE THREAD

**Issue by bfabio** [italia/publiccode-parser-go#49]
Tests should also run when a pull request is made in addition to when it's merged to master.

**Comment by ododa** [comment]
Hi @bfabio ,
I had a quick look at this issue and it seems this needs a couple of toggles to be changed in the circleci project settings.
More specifically, you need to go to **Project Settings > Advanced**, and enable **Build forked pull requests** and  **Only build pull requests**. If you apply these changes I can raise a test PR to verify all's working as expected.

**Comment by sebbalex** [comment]
Hey @bfabio @ododa  I've just toggled  Project Settings > Advanced, and enable Build forked pull requests. It should be fine now.

**Comment by ododa** [comment]
Thanks @sebbalex . I just raised a trivial [PR](https://github.com/italia/publiccode-parser-go/pull/70) but I can't see the build being run as an effect. Can you?

**Comment by sebbalex** [comment]
> Thanks @sebbalex . I just raised a trivial [PR](https://github.com/italia/publiccode-parser-go/pull/70) but I can't see the build being run as an effect. Can you?

Yeah, sorry @ododa I missed a flag, shame on me, could you please add one more commit to your pr. tnx

**Comment by ododa** [comment]
All good! It seems to be working correctly now :+1: . Thanks!

**Comment by sebbalex** [comment]
thanks @ododa
