### ISSUE TITLE
Add CircleCI orb

### ISSUE THREAD

**Issue by bfabio** [italia/publiccode-parser-go#59]
It would be nice to have the functionality of pcvalidate available through a [CircleCI orb](https://circleci.com/orbs/).

**Comment by romain325** [comment]
I could work on it for the Orbtoberfest if you want

**Comment by bfabio** [comment]
Hello @romain325, thanks for your interest. I'm assigning this one to you. :+1:

**Comment by romain325** [comment]
Hello @bfabio, 
You can find the source code [here](https://github.com/romain325/pcvalidateOrb)
and the orb is accessible at romain325/pcvalidate-orb@1.0.0
I'll add a clearer documentation with good examples in the day !!

**Comment by bfabio** [comment]
Done :heart: 

https://circleci.com/developer/orbs/orb/italia/publiccode-parser
https://github.com/italia/publiccode-parser-orb
