### ISSUE TITLE
Accept and map IPA office codes

### ISSUE THREAD

**Issue by alranel** [italia/publiccode-parser-go#6]
IndicePA has two different types of codes:

* iPA code, representing a legal entity (this is what we expect in the `codiceIPA` key)
* office code, representing an office belonging to a legal entity

Such distinction is not very clear, so some people put an office code in the `codiceIPA` key. The parser should be tolerant, and accept office codes too, mapping them to their parent iPA code.

**Comment by sebbalex** [comment]
Since we do have office and main PA merged in same `indicepa_pec` this no longer makes sense.
@libremente thoutgts?

**Comment by libremente** [comment]
Let's close this one!
