### ISSUE TITLE
publiccode.yml version is not properly handled

### ISSUE THREAD

**Issue by bfabio** [italia/publiccode-parser-go#75]
The parser should detect the version in `publiccode-yaml-version` or `publiccodeYmlVersion` and validate the file accordingly to what's defined in that version of the standard.

Depends on #74.

**Comment by libremente** [comment]
We should handle in the "publiccode.yml versioning" strategy.

**Comment by bfabio** [comment]
We now validate against the latest version within that major (eg. `v0.*` is validated against the `v0.3.0` which is now the latest v0 version), and print a warning advising to bump `publiccodeYmlVersion`.

We don't have two major releases yet, but the 90% of machinery is already in place and it's just a matter of deciding the API (we could use go 1.18's generics to return a different Publiccode structure).

Keeping this open as a reminder until we have a new major release.
