### ISSUE TITLE
Update the assets

### ISSUE THREAD

**Issue by bfabio** [italia/publiccode-parser-go#82]
We should update `amministrazioni.txt` and `oembed_providers.json` and possibly come up with a procedure to do it more frequently.

**Comment by libremente** [comment]
Hi @bfabio, could you please furthere elaborate on this issue? Thanks!

**Comment by libremente** [comment]
Ok, probably related to this https://github.com/italia/publiccode-parser-go/pull/81#discussion_r577863200

**Comment by bfabio** [comment]
@libremente yes, `amministrazioni.txt` is compiled inside the binary and must be updated manually to be kept in sync with the current data. Right now we don't have a mechanism to do it automatically at build.
